# The URL the site will be built for
base_url = "https://ohmycloud.github.io"
title = "焉知非鱼"
minify_html = true
taxonomies = [{ name = "tags", feed = true }]

# Theme
theme = "anemone"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "OneHalfLight"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
author = "焉知非鱼"
display_author = true

default_theme = "light"
list_pages = false


header_nav = [
    { url = "/", name_en = "/home", name_zh = "/首页/" },
    { url = "/notes", name_en = "/notes", name_zh = "/笔记/" },
    { url = "/blog", name_en = "/blog", name_zh = "/博客/" },
    { url = "/about", name_en = "/about", name_zh = "/关于/" },
    { url = "/tags", name_en = "/tag", name_zh = "/标签/" },
]
